# fly.toml app configuration file generated for mwpark-crawler on 2026-05-22T15:24:32+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mwpark-crawler'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
